from __future__ import annotations

import requests

from ..fetch import HEADERS

CT_FROM_EXT = {"png": "image/png", "jpg": "image/jpeg", "jpeg": "image/jpeg", "webp": "image/webp",
               "mp4": "video/mp4", "webm": "video/webm"}


def download(url: str, *, timeout: int = 300) -> tuple[bytes, str]:
    """Fetch generated bytes with no credentials — the same way the browser will."""
    r = requests.get(url, headers={"User-Agent": HEADERS["User-Agent"]}, timeout=timeout, stream=True)
    r.raise_for_status()
    data = r.content
    ct = (r.headers.get("content-type") or "").split(";")[0].strip().lower()
    if ct in ("", "application/octet-stream", "binary/octet-stream"):
        ext = url.split("?")[0].rsplit(".", 1)[-1].lower()
        ct = CT_FROM_EXT.get(ext, "application/octet-stream")
    return data, ct


def fetch_reference(url: str, *, timeout: int = 120) -> tuple[bytes, str, str]:
    """Reference bytes, content type and a filename for multipart uploads."""
    data, ct = download(url, timeout=timeout)
    name = url.split("?")[0].rsplit("/", 1)[-1] or "reference"
    if "." not in name:
        name += "." + {v: k for k, v in CT_FROM_EXT.items()}.get(ct, "bin")
    return data, ct, name
